db:
  username: {username.value:postgres}
  password: pass
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 5
    - size: 10
      timeout: 10
  properties:
    first: 123
    second: 567
    third.value: Third
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost, 127.0.0.1
spring:
  profiles:
    active: qa